<#
.SYNOPSIS
Cross-framework time-to-first-paint and process-tree RSS oracle for the Windows
hello arms.

.DESCRIPTION
Every arm renders byte-identical HTML generated from `hello.template.html`
(M-01), differing only in the engine named in the copy. The page emits an image
beacon inside a double requestAnimationFrame -- after the first frame is
composited -- and this harness timestamps its arrival on one external monotonic
clock armed BEFORE the process is spawned. No arm receives privileged
instrumentation; the signal is identical for Keld and every competitor.

Why this shape, from things that actually failed:

  * `document.title` never reaches the native window caption in an embedded
    webview. The framework owns the caption. A title-based signal fails silently
    and identically on Keld, Tauri and Electron -- it looks like "the app never
    painted" rather than "the probe is wrong".
  * `fetch()` is CORS-blocked from the opaque origin these arms render on
    (`with_html` / `NavigateToString`). A subresource `<img>` GET is not.
  * Draining a listener with repeated `GetContextAsync()` calls swallows the
    real beacon: an abandoned accept task still consumes the incoming request.
    Exactly one accept is armed per launch, before spawn.
  * `window-visible` (first titled HWND) is NOT paint. On Keld it fires inside
    the blocking webview build, hundreds of ms before content renders, and
    frameworks differ in when they present the window relative to constructing
    the webview. It is reported here only as a non-paint diagnostic.

Beacons fail closed: a beacon whose nonce is not the one this session is waiting
on is rejected and the run is recorded as a miss rather than silently accepted.

Nonce scope, stated honestly: every Windows arm bakes its HTML in at build time
(Keld a `const`, Tauri `frontendDist`, Electron `app.asar`), so a per-launch
nonce would mean a per-launch rebuild. The nonce is therefore per **session**,
generated by -Prepare and compiled into every arm together. That is enough to
reject a beacon from an earlier session or a binary someone forgot to rebuild --
which is the failure that actually happened here -- but it does NOT distinguish
a late beacon from run 3 arriving during run 4 of the same session. Runs are
serialized, the previous process tree is killed, and one accept is armed at a
time, which bounds that window; it does not close it. A per-launch nonce needs
runtime-loaded content, which is a different measurement lane.

.PARAMETER Port
Listener port. 0 (default) asks the OS for a free port. A fixed port is only
useful for re-running against already-built arms without regenerating them.

.PARAMETER Runs
Measured launches per arm.

.PARAMETER Arms
Which arms to measure. Defaults to the ones whose content is read at runtime and
therefore need no rebuild.

.PARAMETER OutFile
Machine-readable JSON sample file. Raw per-run values are always included, not
just the median.

.EXAMPLE
./Measure-FirstPaint.ps1 -Runs 5 -OutFile samples.json
#>
[CmdletBinding()]
param(
    [switch]$Prepare,
    [int]$Port = 0,
    [int]$Runs = 5,
    [string[]]$Arms = @('keld', 'tauri', 'electron'),
    [string]$OutFile,
    [int]$TimeoutMs = 30000,
    [string]$KeldRepo = 'D:\WORK\keld',
    [string]$BenchRepo = 'D:\WORK\keld-benches'
)

$ErrorActionPreference = 'Stop'
$template = Join-Path $PSScriptRoot 'hello.template.html'
if (-not (Test-Path $template)) { throw "missing template: $template" }
$templateText = [System.IO.File]::ReadAllText($template, [System.Text.Encoding]::UTF8)

# --- arm registry -----------------------------------------------------------
# `Content` is where the arm reads its HTML from. `Embedded` arms bake it in at
# build time and must be rebuilt after the port changes; runtime arms do not.
$registry = @{
    keld = @{
        Engine   = 'WebView2 (Keld)'
        Title    = 'Keld'
        Exe      = Join-Path $KeldRepo 'target\release\keld-host.exe'
        Args     = '--hello'
        Content  = Join-Path $KeldRepo 'crates\keld-wv\src\hello\mod.rs'
        Embedded = $true
    }
    tauri = @{
        Engine   = 'WebView2 (Tauri 2)'
        Title    = 'Tauri Hello'
        Exe      = Join-Path $BenchRepo 'windows\tauri\hello\src-tauri\target\release\tauri-hello.exe'
        Args     = $null
        Content  = Join-Path $BenchRepo 'windows\tauri\hello\src\index.html'
        Embedded = $true
    }
    electron = @{
        Engine   = 'Chromium (Electron)'
        Title    = 'Electron Hello'
        Exe      = $null   # resolved from out/ below
        Args     = $null
        # electron-forge packs src/ into resources/app.asar, so editing the
        # source alone changes nothing the packaged app reads. This is exactly
        # how the first Electron first-paint attempt silently measured a stale
        # copy and reported "no beacon".
        Content  = Join-Path $BenchRepo 'windows\electron\hello\src\index.html'
        Embedded = $true
        Rebuild  = { param($repo) Push-Location (Join-Path $repo 'windows\electron\hello'); try { Invoke-Native { npx electron-forge package } "electron package" } finally { Pop-Location } }
    }
}

function Resolve-ElectronExe {
    $out = Join-Path $BenchRepo 'windows\electron\hello\out'
    if (-not (Test-Path $out)) { return $null }
    (Get-ChildItem $out -Recurse -Filter '*.exe' -ErrorAction SilentlyContinue |
        Where-Object { $_.Name -notmatch 'crashpad|Uninstall' } |
        Select-Object -First 1).FullName
}

# Windows PowerShell 5.1 file IO is a trap for source files: Get-Content
# defaults to ANSI and mangles UTF-8 (an em dash round-trips to "â€”"), and
# Set-Content -Encoding utf8 emits a BOM Rust and git do not want. Both of those
# silently corrupted keld-wv's hello source on the first attempt. Go through
# .NET with an explicit no-BOM encoding instead.
$script:Utf8NoBom = [System.Text.UTF8Encoding]::new($false)
function Read-Utf8([string]$path) { [System.IO.File]::ReadAllText($path, [System.Text.Encoding]::UTF8) }
function Write-Utf8([string]$path, [string]$text) { [System.IO.File]::WriteAllText($path, $text, $script:Utf8NoBom) }

function Render-Html([string]$engine, [string]$title, [int]$port, [string]$nonce) {
    $templateText.Replace('__ENGINE__', $engine).
                  Replace('__TITLE__', $title).
                  Replace('__PORT__', "$port").
                  Replace('__NONCE__', $nonce)
}

# Native tools (cargo, npx) write progress to stderr. With
# $ErrorActionPreference = 'Stop' PowerShell turns that into a terminating
# NativeCommandError even on a successful build, so run them with Continue and
# judge the real exit code instead.
function Invoke-Native([scriptblock]$block, [string]$what) {
    $prev = $ErrorActionPreference
    $ErrorActionPreference = 'Continue'
    try { & $block *>&1 | Out-Null; $code = $LASTEXITCODE }
    finally { $ErrorActionPreference = $prev }
    if ($code -ne 0) { throw "$what failed (exit $code)" }
}

function Get-Descendants([int]$rootPid) {
    $all = Get-CimInstance Win32_Process | Select-Object ProcessId, ParentProcessId, Name
    $out = @(); $queue = @($rootPid)
    while ($queue.Count -gt 0) {
        $cur = $queue[0]; $queue = @($queue | Select-Object -Skip 1)
        foreach ($c in $all | Where-Object { $_.ParentProcessId -eq $cur -and $_.Name -ne 'conhost.exe' }) {
            $out += $c; $queue += $c.ProcessId
        }
    }
    $out
}

# --- listener ---------------------------------------------------------------
# Bound once for the session: embedded arms bake the port in, so re-binding per
# launch would mean rebuilding per launch.
$probe = [System.Net.Sockets.TcpListener]::new([System.Net.IPAddress]::Loopback, $Port)
$probe.Start()
$realPort = $probe.LocalEndpoint.Port
$probe.Stop()

$listener = [System.Net.HttpListener]::new()
$listener.Prefixes.Add("http://127.0.0.1:$realPort/")
$listener.Start()
Write-Host "listener: http://127.0.0.1:$realPort/ (requested $Port)"

# --- prepare ----------------------------------------------------------------
# Compiles the beacon (port + session nonce) into every arm and rebuilds them.
# Must be re-run whenever the port changes, which is why the port is bound once
# per session rather than per launch.
$statePath = Join-Path $PSScriptRoot '.session-state.json'

if ($Prepare) {
    $sessionNonce = [guid]::NewGuid().ToString('N')
    foreach ($arm in $Arms) {
        $cfg = $registry[$arm]
        $html = Render-Html $cfg.Engine $cfg.Title $realPort $sessionNonce
        Write-Host "prepare: $arm"

        if ($arm -eq 'keld') {
            # Keld's hello HTML is a Rust `const`, not a file. Splice the beacon
            # in before </body> rather than rewriting the const wholesale, so the
            # measured markup still matches what ships.
            $src = Read-Utf8 $cfg.Content
            $beacon = ($html -split '(?s)<script>')[1]
            $beacon = '  <script>' + ($beacon -replace '(?s)</script>.*$', '</script>')
            if ($src -match '(?s)KELD_BENCH_BEACON') { throw "keld source already patched; restore it first" }
            $src = $src -replace '(?s)(\n)(</body>\r?\n</html>"#;)', "`$1$beacon`n// KELD_BENCH_BEACON`n`$2"
            Write-Utf8 $cfg.Content $src
            Invoke-Native { cargo build --release --manifest-path (Join-Path $KeldRepo 'Cargo.toml') -p keld-host } "keld build"
        }
        else {
            Write-Utf8 $cfg.Content $html
            if ($arm -eq 'tauri') {
                Push-Location (Join-Path $BenchRepo 'windows\tauri\hello')
                try { Invoke-Native { npx tauri build --no-bundle } "tauri build" } finally { Pop-Location }
            }
            elseif ($cfg.Rebuild) { & $cfg.Rebuild $BenchRepo }
        }
    }
    [pscustomobject]@{ nonce = $sessionNonce; port = $realPort; prepared_utc = (Get-Date).ToUniversalTime().ToString('o') } |
        ConvertTo-Json | Set-Content $statePath -Encoding utf8
    Write-Host "prepared: port $realPort, nonce $sessionNonce"
    Write-Host "NOTE: arm sources now contain the beacon. Restore them before committing product code."
    $listener.Stop(); $listener.Close()
    return
}

if (-not (Test-Path $statePath)) { $listener.Stop(); throw "no session state: run with -Prepare first" }
$state = Get-Content $statePath -Raw | ConvertFrom-Json
if ($state.port -ne $realPort) {
    $listener.Stop()
    throw "port changed ($($state.port) -> $realPort); arms were built for the old port. Re-run with -Prepare -Port $($state.port), or -Prepare to rebuild."
}
$sessionNonce = $state.nonce

$samples = [System.Collections.Generic.List[object]]::new()

try {
    foreach ($arm in $Arms) {
        if (-not $registry.ContainsKey($arm)) { throw "unknown arm '$arm'" }
        $cfg = $registry[$arm]
        if ($arm -eq 'electron') { $cfg.Exe = Resolve-ElectronExe }
        if (-not $cfg.Exe -or -not (Test-Path $cfg.Exe)) {
            Write-Warning "$arm : executable not found; skipping. Build it first."
            continue
        }

        $hash = (Get-FileHash $cfg.Exe -Algorithm SHA256).Hash
        $ver = (Get-Item $cfg.Exe).VersionInfo.ProductVersion

        for ($i = 1; $i -le $Runs; $i++) {
            # Session-scoped: every arm baked this in at -Prepare time. A binary
            # that missed the rebuild carries an old nonce and is rejected below
            # rather than quietly contributing a wrong number.
            $nonce = $sessionNonce

            # Exactly one accept, armed before spawn.
            $ctxTask = $listener.GetContextAsync()
            # .NET Process.Start, not the Start-Process cmdlet. The cmdlet costs
            # 450-700 ms between the call and the child's main() on this machine
            # (measured via a wall-clock printed at child entry), which inflated
            # every arm's published first-paint absolutes by roughly half a
            # second. The spawn offset cannot be assumed zero either way, so it
            # is measured per run below and recorded in the sample.
            $psi = [System.Diagnostics.ProcessStartInfo]::new()
            $psi.FileName = $cfg.Exe
            if ($cfg.Args) { $psi.Arguments = $cfg.Args }
            $psi.WorkingDirectory = (Split-Path $cfg.Exe)
            $psi.UseShellExecute = $false
            $spawnWall = [DateTimeOffset]::UtcNow.ToUnixTimeMilliseconds()
            $sw = [Diagnostics.Stopwatch]::StartNew()
            $p = [System.Diagnostics.Process]::Start($psi)

            $hwndMs = $null; $paintMs = $null; $reject = $null
            while ($sw.ElapsedMilliseconds -lt $TimeoutMs) {
                if ($ctxTask.Wait(5)) {
                    $elapsed = $sw.ElapsedMilliseconds
                    $ctx = $ctxTask.Result
                    $got = $ctx.Request.QueryString['nonce']
                    $ctx.Response.StatusCode = 204
                    $ctx.Response.Close()
                    if ($got -eq $nonce) {
                        $paintMs = $elapsed
                    } else {
                        # Stale/foreign beacon: fail closed, do not attribute.
                        $reject = "nonce mismatch (got '$got')"
                    }
                    break
                }
                $p.Refresh()
                if ($p.HasExited) { $reject = "process exited before painting"; break }
                if (-not $hwndMs -and $p.MainWindowHandle -ne 0 -and $p.MainWindowTitle) {
                    $hwndMs = $sw.ElapsedMilliseconds
                }
            }
            if (-not $paintMs -and -not $reject) { $reject = "timeout after ${TimeoutMs}ms" }

            # RSS only after the paint condition, and only for our own tree.
            $mainKb = $null; $helperKb = $null; $procs = $null
            if ($paintMs) {
                Start-Sleep -Seconds 4
                $desc = Get-Descendants $p.Id
                $p.Refresh()
                $mainKb = [math]::Round($p.WorkingSet64 / 1KB)
                $h = @($desc | ForEach-Object { Get-Process -Id $_.ProcessId -ErrorAction SilentlyContinue } | Where-Object { $_ })
                $helperKb = [math]::Round((($h | Measure-Object WorkingSet64 -Sum).Sum) / 1KB)
                $procs = $h.Count + 1
            }

            Stop-Process -Id $p.Id -Force -ErrorAction SilentlyContinue
            Get-Descendants $p.Id | ForEach-Object { Stop-Process -Id $_.ProcessId -Force -ErrorAction SilentlyContinue }
            Start-Sleep -Seconds 2

            $samples.Add([pscustomobject]@{
                arm          = $arm
                run          = $i
                first_paint_ms = $paintMs
                window_visible_ms = $hwndMs   # diagnostic only; NOT paint
                main_rss_kb  = $mainKb
                helper_rss_kb = $helperKb
                processes    = $procs
                rejected     = $reject
                spawn_wall_utc_ms = $spawnWall
                exe          = $cfg.Exe
                exe_sha256   = $hash
                exe_version  = $ver
                engine       = $cfg.Engine
                command      = "$($cfg.Exe) $($cfg.Args)".Trim()
                nonce        = $nonce
            })
            $status = if ($paintMs) { "paint ${paintMs}ms" } else { "MISS: $reject" }
            Write-Host ("  {0,-9} run {1}/{2}  {3}" -f $arm, $i, $Runs, $status)
        }
    }
}
finally {
    $listener.Stop()
    $listener.Close()
}

# --- report -----------------------------------------------------------------
$meta = [pscustomobject]@{
    measured_utc = (Get-Date).ToUniversalTime().ToString('o')
    os           = (Get-CimInstance Win32_OperatingSystem).Caption
    os_version   = [System.Environment]::OSVersion.Version.ToString()
    arch         = $env:PROCESSOR_ARCHITECTURE
    keld_sha     = (& git -C $KeldRepo rev-parse HEAD 2>$null)
    bench_sha    = (& git -C $BenchRepo rev-parse HEAD 2>$null)
    listener_port = $realPort
    runs         = $Runs
    harness      = 'windows/bench/Measure-FirstPaint.ps1'
}

"`n=== medians (misses excluded, count shown) ==="
foreach ($g in $samples | Group-Object arm) {
    $ok = @($g.Group | Where-Object { $_.first_paint_ms })
    if ($ok.Count -eq 0) { "{0,-9} NO VALID PAINT ({1} runs)" -f $g.Name, $g.Group.Count; continue }
    $fp = @($ok.first_paint_ms | Sort-Object)
    $mr = @($ok.main_rss_kb | Sort-Object)
    $hr = @($ok.helper_rss_kb | Sort-Object)
    "{0,-9} first_paint {1,6} ms | main {2,7} KB | helpers {3,8} KB | {4} procs | {5}/{6} valid" -f `
        $g.Name, $fp[[int]($fp.Count / 2)], $mr[[int]($mr.Count / 2)], $hr[[int]($hr.Count / 2)],
        ($ok[0].processes), $ok.Count, $g.Group.Count
}

if ($OutFile) {
    [pscustomobject]@{ meta = $meta; samples = $samples } |
        ConvertTo-Json -Depth 6 | Set-Content $OutFile -Encoding utf8
    "`nraw samples: $OutFile"
}
